version: '3'

services:
  
  redis-pdf:

    restart: always
    image: redis:latest
    expose:
      - "6379"
    networks:
      - ai-web
    volumes:
    - redispdf:/data

  convert:
    restart: always
    build: ./convert
    volumes:
     - pdfdata:/data
    environment:
     - PDFPATHORIGIN=${PDFPATHORIGIN}
     - REDIS_HOST=${REDIS_HOST}
    depends_on: 
      - redis-pdf
    networks:
      - ai-web

  uploadws:
    build: ./websocket/
    environment:
     - REDIS_HOST=${REDIS_HOST}
    labels:
        - "traefik.backend=uploadws"
        - "traefik.docker.network=ai-web"
        - "traefik.enable=true"
        - "traefik.port=3001"
        - "traefik.frontend.rule=Host:uploadws.${D_HOST}"
        - "traefik.frontend.entryPoints=http"
    expose:
      - "3001"
    
    networks:
      - ai-web
    depends_on: 
      - redis-pdf
    working_dir : /usr/src/app
    command: sh -c 'node ./src/server.js'

  converted:
    environment:
      - DESTINATION=/data
    image: python:latest
    labels:
        - "traefik.backend=converted"
        - "traefik.docker.network=ai-web"
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.frontend.rule=Host:converted.${D_HOST}"
        - "traefik.frontend.entryPoints=http"
    expose:
      - "8000"
    volumes:
      - pdfdata:/data
    networks:
      - ai-web
    working_dir : /data/converted
    command: sh -c 'python -m http.server 8000'

  uploadpdf:
    environment:
      - DESTINATION=/data
      - REDIS_HOST=${REDIS_HOST}
    build: ./upload/
    labels:
        - "traefik.backend=uploadpdf"
        - "traefik.docker.network=ai-web"
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:uploadpdf.${D_HOST}"
        - "traefik.frontend.entryPoints=http"
    expose:
      - "8080"
    volumes:
      - pdfdata:/data
    networks:
      - ai-web
    depends_on: 
      - redis-pdf
    working_dir : /usr/src/app
    command: sh -c 'node ./src/index.js'

  frontend:
    build: ./frontend-rewrite/
    labels:
        - "traefik.backend=frontend"
        - "traefik.docker.network=ai-web"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:convert.${D_HOST}"
        - "traefik.frontend.entryPoints=http"
    expose:
      - "80"
    networks:
      - ai-web
      
   


networks:
  ai-web:
    external: true

volumes:
  
  pdfdata: {}
  
  redispdf: {}
  
  
 
  
