version: '3'

services:
  traefik:
    image: traefik:1.5
    command: --web --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" --docker
    restart: always
    ports:
      - 80:80
      - 443:443
      - 10002:8080
      - 10001:8082
      - 10000:8081
    labels:
      - "traefik.frontend.rule=Host:docker.lbr.lu"
      - "traefik.frontend.entryPoints=http-admin"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /opt/traefik/acme.json:/etc/traefik/acme.json


  redis-pdf:

    restart: always
    image: redis:latest
    expose:
      - "6379"
    networks:
      - web
  
    volumes:
    - ./redis:/data


  convert:
    restart: always
    build: ./convert
    volumes:
     - './convert:/usr/src/app'
     - /data:/data
    environment:
     - PDFPATHORIGIN=${PDFPATHORIGIN}
    networks:
      - web

  websocket:
    build: ./websocket/
    labels:
        - "traefik.backend=uploadws"
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.port=3001"
        - "traefik.frontend.rule=Host:uploadws.lbr.lu"
        - "traefik.frontend.entryPoints=http"
    expose:
      - "3001"
    
    networks:
      - web
    working_dir : /usr/src/app
    command: sh -c 'node ./src/server.js'

  converted:
    environment:
      - DESTINATION=/data
    image: python:latest
    labels:
        - "traefik.backend=converted"
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.frontend.rule=Host:converted.lbr.lu"
        - "traefik.frontend.entryPoints=http"
    expose:
      - "8000"
    volumes:
      - /data:/data
    networks:
      - web
    working_dir : /data/converted
    command: sh -c 'python -m http.server 8000'

  upload:
    environment:
      - DESTINATION=/data
    build: ./upload/
    labels:
        - "traefik.backend=uploadpdf"
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:uploadpdf.lbr.lu"
        - "traefik.frontend.entryPoints=http"
    expose:
      - "8080"
    volumes:
      - /data:/data
    networks:
      - web
    working_dir : /usr/src/app
    command: sh -c 'node ./src/index.js'

  frontend:
    build: ./webuploadpdf/
    labels:
        - "traefik.backend=uploadweb"
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:convertpdf.lbr.lu"
        - "traefik.frontend.entryPoints=http"
    expose:
      - "8080"
    networks:
      - web
      
   


networks:
  web:
    external: true

volumes:
  pdferrordb : {}
  aidata: {}
  portainerdata: {}
  mongodb: {}
  postgres-data: {}
  xwiki-data: {}
 
  
