version: '3'

services:

 traefik:
    image: traefik:1.5
    command: --web --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" --docker
    restart: always
    ports:
      - 80:80
      - 443:443
      - 10002:8080
      - 10001:8082
      - 10000:8081
    labels:
      - "traefik.domain=pdfexp.com"
      - "traefik.frontend.rule=Host:traefik.pdfexp.com"
      - "traefik.frontend.entryPoints=http, https"
    networks:
      - pdf-web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/acme.json:/etc/traefik/acme.json


 redis-pdf:

    restart: always
    image: redis:latest
    networks:
      - pdf-web
    volumes:
     - redispdf:/data

 convert:
    restart: always
    image: convert-pdf:latest
    build: ./convert

    deploy:
      replicas: 10
    volumes:
     - pdfdata:/data
    environment:
     - PDFPATHORIGIN=/data/
     - REDIS_HOST=redis-pdf
    depends_on: 
      - redis-pdf
    networks:
      - pdf-web

 uploadws:
    image: websocket-pdf:latest
    build: ./websocket/
    environment:
     - REDIS_HOST=redis-pdf
    labels:
        - "traefik.backend=uploadws"
        - "traefik.docker.network=pdf-web"
        - "traefik.enable=true"
        - "traefik.port=3001"
        - "traefik.frontend.rule=Host:uploadws.pdfexp.com"
        - "traefik.frontend.entryPoints=http, https"
    networks:
      - pdf-web
    depends_on: 
      - redis-pdf
    working_dir : /usr/src/app
    command: sh -c 'node ./src/server.js'

 converted:
    environment:
      - DESTINATION=/data
    image: python:latest
    labels:
        - "traefik.backend=converted"
        - "traefik.docker.network=pdf-web"
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.frontend.rule=Host:converted.pdfexp.com"
       # - "traefik.frontend.entryPoints=https"
        - "traefik.frontend.entryPoints=http, https"

    volumes:
      - pdfdata:/data
    networks:
      - pdf-web
    working_dir : /data/converted
    command: sh -c 'python -m http.server 8000'

 uploadpdf:
    environment:
      - DESTINATION=/data
      - REDIS_HOST=redis-pdf
    image: upload-pdf:latest
    build: ./upload/
    labels:
        - "traefik.backend=uploadpdf"
        - "traefik.docker.network=pdf-web"
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:uploadpdf.pdfexp.com"
      #  - "traefik.frontend.redirect.entryPoint: "http,https"
        - "traefik.frontend.entryPoints=http, https"
 
    volumes:
      - pdfdata:/data
    networks:
      - pdf-web
    depends_on: 
      - redis-pdf
    working_dir : /usr/src/app
    command: sh -c 'node ./src/index.js'

 frontend:
    image: frontend-pdf:latest
    build: ./frontend-rewrite/
    labels:
        - "traefik.backend=frontend"
        - "traefik.docker.network=pdf-web"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:pdfexp.com"
       # - "traefik.frontend.redirect.entryPoint: "https"
        - "traefik.frontend.entryPoints=http, https"
    networks:
      - pdf-web
      
   


networks:
  pdf-web:
    external: true
  
volumes:
  
  pdfdata: {}
  
  redispdf: {}
  
  
 
  