

debug = false
logLevel = "ERROR"


[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "pdfexp.com"
  watch = true
  exposedbydefault = false
defaultEntryPoints = [ "http", "https"]

# Entrypoints, http and https
[entryPoints]

# http should not be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
# https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


[acme]
 email = "aureussz@gmail.com"
 storage = "/etc/traefik/acme.json"
 entryPoint = "https"
 onHostRule = true

    
 [acme.httpChallenge]
 entryPoint = "http"