

debug = true
logLevel = "INFO"


[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "pdfexp.com"
  watch = true
  exposedbydefault = false

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "examples/traefik.crt"
      keyFile = "examples/traefik.key"


[acme]
 email = "aureussz@gmail.com"
 storage = "/etc/traefik/acme.json"
 entryPoint = "https"
 onHostRule = true

    
 [acme.httpChallenge]
 entryPoint = "http"