
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: convert
  name: convert
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: convert
    spec:
      containers:
      - env:
        - name: PDFPATHORIGIN
          value: /data
        - name: REDIS_HOST
          value: redis-pdf
        image: gcr.io/api-project-213114800966/convert
        name: convert
        resources: {}
        
      restartPolicy: Always

      
status: {}



