apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: converted
  name: converted
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: converted
    spec:
      containers:
      - args:
        - sh
        - -c
        - mkdir /data &&
        - mkdir /data/converted &&
        - python -m http.server 8000
        env:
        - name: DESTINATION
          value: /data
        image: python:latest
        name: converted
        resources: {}
        workingDir: /data/converted
      volumeMounts:
        - mountPath: "/apps/data"
          name: pdfdata
      volumes:
      - name: pdfdata
        nfs:
          path: "/data"
          server: 10.132.0.10
      restartPolicy: Always
    
 
status: {}
